### ISSUE TITLE
Rename `CHAIR_W3CID` variable

### ISSUE THREAD

**Issue by tidoust** [w3c/tpac-breakouts#103]
On top of providing a mapping between names of chairs and their W3C ID, the variable may also be used to provide a mapping between a group names and their W3C ID. It should be renamed to something more neutral accordingly.

(via #99)

**Comment by ianbjacobs** [comment]
How about W3CID_MAP ?

**Comment by tidoust** [comment]
Variable renamed in the code and in existing repositories for upcoming events. Wiki documentation also updated.
