### ISSUE TITLE
Support rooms dedicated to specific meetings

### ISSUE THREAD

**Issue by tidoust** [w3c/tpac-breakouts#128]
During TPAC, the room where the AC takes place is sometimes dedicated to it and not generally available for other group meetings.

**Comment by ianbjacobs** [comment]
@tidoust, I have reached out to find out which room is for the AC. Thanks for adding this feature!

**Comment by ianbjacobs** [comment]
I tested this feature today and it seems to work. I added "Room (80) (VIP)" to the project and then assigned it by hand to a particular group. Regenerating the schedule with the same seed and "preserve all" caused the tool to generate only that session in that particular room. (I also tested the room name as "Room (VIP)" and got, usefully, a capacity error.)

**Comment by tidoust** [comment]
Good! I also made a short update to the documentation to mention VIP rooms.
