### ISSUE TITLE
Slot adjustment did not appear in generated HTML

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/tpac-breakouts#129]
In the tpac2024-meetings project, we have hard-coded an adjusted slot end time:

  Tuesday, 14:00; Tuesday, 16:30-18:00<17:00>

But the generated HTML says:

  Tuesday, 14:00 - 18:00

**Comment by ianbjacobs** [comment]
This seems to now be working, so closing.

**Comment by tidoust** [comment]
Reopening as I'd be very surprised if it worked: there is no code in the HTML generation logic that looks at the actual start/end times...

**Comment by tidoust** [comment]
Ah no, you're right, it works. The code reports the merged meetings, and the merge logic does support the start/end time adjustments.
