### ISSUE TITLE
Where to collect breakout session proposals

### ISSUE THREAD

**Issue by tidoust** [w3c/tpac-breakouts#15]
Proposals for breakout sessions have been collected through a Wiki page (e.g. the one for [2022](https://www.w3.org/wiki/TPAC/2022/SessionIdeas)). This issue looks at main pros and cons of different mechanisms which could be used to create a [single source of truth](https://en.wikipedia.org/wiki/Single_source_of_truth) that could ideally be processed automatically.

# Collect proposals on a Wiki page

Pros:
- Easy to edit a Wiki page.
- All proposals are visible at once.
- Easy to adjust the template and perform a search+replace across proposals to reflect changes as needed.
- Easy to track updates and rollback to a previous state if needed.
- Through manual interventions to curate the list of proposals on a regular basis, it's relatively easy to create a tool that converts the list of proposals to a structured list that follows some JSON format.
- We're used to that approach already.

Cons:
- Currently requires manual processing to convert the list to a JSON structure that can then be validated and reused, e.g. to _enter the grid_. That manual processing is error prone, especially because...
- Easy for people not to follow the [provided template](https://www.w3.org/wiki/TPAC/2022/SessionIdeas#How_to_propose_a_session), or to be creative, starting with the list of proposers (with or without email, with or without "and", etc.). This requires more manual interventions to fix the proposal so that it may be converted to other formats (notably HTML).
- No clean separation between fields that are up to proposers and fields that are to maintained by organizers, such as annotations to set the breakout room and slot.
- "This wiki is restricted to members of one or several W3C groups". It may not be that easy for everyone to edit a Wiki page.

# Collect proposals as GitHub issues

Pros:
- [GitHub's form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema) could be used to impose the session template upon submission.
- Relatively easy to view all proposals at once, by listing open GitHub issues (which could be flagged with a `proposal` label)
- Useful to gather comments on proposals, point proposers to related proposals, suggest changes, etc.
- Easy to use labels to annotate proposals for organizers (e.g. track, room, slot, approval).
- Relatively easy to create automated jobs that run whenever an issue is updated to validate the proposal, possibly flag it as invalid, convert it to JSON, etc.
- W3C's calendaring system uses [GitHub Flavoured Markdown](https://guides.github.com/features/mastering-markdown/) already, no conversion needed for structured info.

Cons:
- [GitHub's form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema) is fairly limited. There are no provisions for arrays for instance, which could typically be used to tell proposers apart.
- [GitHub's form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema) is fairly limited (bis). Once the issue has been created, the proposer may further edit it in place, which is both good to update the info it contains, and bad because these edits are unconstrained (the initial form no longer gets used). Once that happens, we're back to the same issue as with Wiki: manual intervention from organizers is required to fix (reporting validation errors automatically could be envisioned, but that seems heavy at first sight, and not very welcoming feedback for newcomers willing to propose a session).
- Above point means that, in practice, automation may often break when proposers update their proposal. We're back to the same problem as with the Wiki.
- Validation jobs will often break with annotations too. For instance, to swap proposals between rooms, an organizer will typically (1) remove the first room label from the first session, (2) add the second room label to the first session, (3) remove the second room label from the second session and then (4) add the first room label from the second session. If jobs run after each update, validation will fail after (2), because the update creates a temporary scheduling conflict (two sessions at the same time in the same room).
- Requires a GitHub account. Basically all groups use GitHub nowadays, so that shouldn't be too much of a burden.

# Collect proposals through WBS

Pros:
- Easy to constrain the fields, even for updates
- Integrated with W3C users database

Cons:
- Still no support for arrays
- WBS forms are per proposer, not per idea. One proposer can only submit one proposal.
- Not sure how to automate retrieval of WBS results in practice, but that should be doable :)

# Collect proposals through some custom web app

Pros:
- Easy to create the right HTML form and get structured results right away

Cons:
- Hard to integrate with some login mechanism to identify proposers and allow them to update their proposals after submission in particular.
- Hard to integrate features such as history tracking or comments on proposals. Or rather, it's easy to end up with a long list of features that seem easy on paper but would require dev resources that we don't have.
- Requires deploying the logic somewhere.

**Comment by humeranoor** [comment]
Interesting comparison. Thanks for putting this together. 

I stumbled on this page while trying to find where to submit breakout session proposals for TPAC 2023. Do we have a conclusion?

**Comment by tidoust** [comment]
Ah, not yet, we will likely decide on the road we'll take in the next few weeks. I don't think we'll open submission of breakout session proposals for TPAC 2023 before June in any case!

**Comment by tidoust** [comment]
Closing this issue to note that we decided to collect breakout session proposals through a GitHub repository this year (we will use a dedicated repository for that, and will continue use this repository to track progress on features, tools and questions). Submission of breakout session proposals is not yet open (but then TPAC registration is not open either).
