### ISSUE TITLE
One year update: fenced frames with local unpartitioned data access

### ISSUE THREAD

**Issue by shivanigithub** [w3c/tpac-breakouts#151]
**Session description**
This breakout session will serve as a 1 year update to the "fenced frames with local unpartitioned data access" project. We will:

- Briefly recap the [fenced frames with local unpartitioned data access](https://github.com/WICG/fenced-frame/blob/master/explainer/fenced_frames_with_local_unpartitioned_data_access.md) explainer.
- Go over implementation progress in Chrome and highlight solutions that may be valuable to other developers.

**Session goal**
To present implementation and design updates, and welcome feedback on any use cases that may benefit from this.

**Additional session chairs (Optional)**
@VergeA , @jkarlin 

**Who can attend**
Anyone may attend (Default)

**IRC channel (Optional)**

**Other sessions where we should avoid scheduling conflicts (Optional)**
No response

**Instructions for meeting planners (Optional)**
No response

**Agenda for the meeting.**
No response

**Comment by tidoust** [comment]
Hi @shivanigithub. No problem with the breakout session proposal, but this is not the right repository to raise it! This repository just hosts the tools used to organize breakout sessions during W3C TPAC events. Breakout session proposals are rather recorded in dedicated repositories, one per breakout event.

For TPAC 2024, the repository is [`w3c/tpac2024-breakouts`](https://github.com/w3c/tpac2024-breakouts/issues). Could you report the proposal over there using the [new issue template](https://github.com/w3c/tpac2024-breakouts/issues/new?assignees=&labels=session&projects=&template=session.yml)?

**Comment by shivanigithub** [comment]
> Hi @shivanigithub. No problem with the breakout session proposal, but this is not the right repository to raise it! This repository just hosts the tools used to organize breakout sessions during W3C TPAC events. Breakout session proposals are rather recorded in dedicated repositories, one per breakout event.
> 
> For TPAC 2024, the repository is [`w3c/tpac2024-breakouts`](https://github.com/w3c/tpac2024-breakouts/issues). Could you report the proposal over there using the [new issue template](https://github.com/w3c/tpac2024-breakouts/issues/new?assignees=&labels=session&projects=&template=session.yml)?

Sorry about that. Created https://github.com/w3c/tpac2024-breakouts/issues/40 
Closing this issue.
