### ISSUE TITLE
Tool to extract session chair contact information

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/tpac-breakouts#18]
For communications before and after TPAC with session chairs, it would be handy to be able to extract the contact information for email.

**Comment by ianbjacobs** [comment]
Proposal:

* By default, person who raised the issue is (at least one of) the session proposals for the purposes of communications. 
* The person who raised the issue can identify additional proponents through a form field. They identify proponents via their GitHub labels.
* In case we need to merge sessions, we will do so manually, possibly by creating a new issue. So in some cases (like this), the proposer of the session will not be relevant for ongoing communications.
* Internally, we will map GitHub identities to W3C identities (where there is a binding) to extract contact information.

**Comment by ianbjacobs** [comment]
Solution: We will get info from W3C database via link with W3C accounts. When there is no link to a W3C account, we will work around the situation (e.g., by reaching out to the GitHub account owner).

**Comment by tidoust** [comment]
Local mapping done through a `CHAIR_W3CID` environment (and GitHub repo) variable. What remains is a documentation effort, tracked in #27.
