### ISSUE TITLE
Suggest that people add emojis to issue descriptions to gauge level of interest

### ISSUE THREAD

**Issue by tidoust** [w3c/tpac-breakouts#35]
Via @sideshowbarker: "As a way to gauge the level of interest in each session proposal, would it be good to suggest somewhere that people add emojis to the issue descriptions?"

This could be broadened to issue comments: one of the arguments for switching to GitHub was that it facilitated preliminary discussions on proposals. I don't think that we encourage such discussions anywhere.

**Comment by ianbjacobs** [comment]
I've mentioned showing support through emojis in the following places:

* TPAC site on the [schedule page](https://www.w3.org/2023/09/TPAC/schedule.html#wednesday)
* [README of TPAC 2023 breakout repo](https://github.com/w3c/tpac2023-breakouts#readme)
* [Good practices documentation](https://github.com/w3c/tpac-breakouts/wiki/Good-Practices-for-Session-Chairs#how-to-propose-a-session), although that is mostly for session proponents. But it could help to draw this option to their attention.
* Next two [communications about breakouts](https://github.com/w3c/tpac2023-breakouts/wiki/Meeting-Planner-Resources#communications) will mention this.

@sideshowbarker, thank you for the feedback. I'm going to close the issue but if we (or you) see other opportunities to encourage people to show support through emojis, we can make more changes.

Also, thank you for the feedback!
