### ISSUE TITLE
Contact information for all session chairs?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/tpac-breakouts#38]
We send several messages before and after TPAC to "session chairs." It would be handy to have a (team-visible) list email addresses of all session chairs (ideally both those proposing the session and those named as co-chairs).

**Comment by tidoust** [comment]
As a first step, I added a [list-chairs tool/job](https://github.com/w3c/tpac2023-breakouts/actions/workflows/list-chairs.yml) to list the information we have about session chairs. Some caveats:

1. Job needs to be triggered manually.
1. Results currently appear in the logs of the job, coz' information should not be publicly available.
2. There is no way to retrieve user info from a W3C ID, job can only point at the `https://www.w3.org/users/xxxx` page when all it has is the user's W3C ID.

**Comment by tidoust** [comment]
Well, we shouldn't run the job as-is in practice. I thought action log details would be only visible by repo owners but, while they are not public, they seem to be visible by anyone who's logged in to GitHub. To be improved :)

**Comment by ianbjacobs** [comment]
Based on further chatting, I'm going to close this one with the assumption we will manually collect email addresses.
