### ISSUE TITLE
Case-sensitivity important to GitHub identity in mapping to W3C identity?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/tpac-breakouts#42]
In one issue, a co-chair was identified using a GitHub identity with `@CamelCase`. I mapped that to a W3C identity and the validation failed to find the W3C identity. I surmised that the Github identity needed to be lowercase, and when I changed the mapping that worked.

Is a GitHub id case-sensitive? If not, could we ignore case when validating the mapping?

**Comment by tidoust** [comment]
Just to clarify: what was required wasn't lowercase per se, but the same case as in the **raw** issue body. GitHub tweaks the rendering of GitHub identities to display them using whatever case the GitHub user wants to use (in this case `@CamelCase`).

I made the code case-insensitive, so no need to worry about that anymore :)
