### ISSUE TITLE
Replace inline tabs with spaces in calendar entries

### ISSUE THREAD

**Issue by tidoust** [w3c/tpac-breakouts#45]
People may use tabs in the session description in GitHub, which get turned into blockquotes when the calendar entries are ingested in the schedule page. The update-calendar script should replace tabs with spaces to avoid that.

**Comment by ianbjacobs** [comment]
Hi @tidoust,

I suspect the fix for this is in calendar.mjs. Is this something we should fix in time for Breakouts Day?

**Comment by tidoust** [comment]
Clarifying the problem now that I've looked into it:

[GitHub Flavoured Markdown](https://github.github.com/gfm/#tabs) does not convert inline tabs to blockquotes, whereas the tool that converts the markdown to HTML does. Tabs at the start of a line should be preserved, they signal an intent to create a blockquote. We should only replace inline tabs.

I doubt we'll run into this often, but the fix is straightforward and we already ran into this before... I'll fix it.
