### ISSUE TITLE
Manage when issues close after scheduling has begun

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/tpac-breakouts#46]
Per @tidoust:

What's missing is a job triggered when an issue is closed that:
- removes the session from the project
- cancels the calendar entry
- removes references to the issue in the conflict section of other issues
- re-validates sessions that got updated (if there was a real conflict due to the now closed issue, this conflict should be gone)

**Comment by tidoust** [comment]
I can tell that you don't like #30 :))
And yet it includes the same comment: https://github.com/w3c/tpac-breakouts/issues/30#issuecomment-1707670283
