### ISSUE TITLE
No calendar setting for sessions "restricted to TPAC participants"

### ISSUE THREAD

**Issue by tidoust** [w3c/tpac-breakouts#49]
Breakout sessions may be restricted to TPAC participants, but there is no way to restrict showing the join information to TPAC participants in calendar entries. The closest setting is "People invited to the event and holders of a W3C account with Member access", but there are non-member people who may be TPAC participants (e.g., people participating in a CG that meets at TPAC).

Systems team says: "we could add the ACL next year" (no UI change needed, calendar events are already linked to TPAC through the notion of "Big Event")

**Comment by ianbjacobs** [comment]
I sent a request to the Systems Team today.

**Comment by tidoust** [comment]
Closing. A new setting was put in place in the calendar. Tooling was updated to support it.
