### ISSUE TITLE
IRC: channel operator rights

### ISSUE THREAD

**Issue by tidoust** [w3c/tpac-breakouts#52]
When the bot creates the IRC channel, it gains channel operator rights. When it leaves, no one has channel operator rights by default. This means that no one can change the topic.

**Comment by ianbjacobs** [comment]
More detailed comments:

* Should TPAC breakout managers have superpowers on IRC during the breakouts day? (Granted then revoked by systeam).
* The breakout bot should also have sufficient powers to set up a channel title in the case where there are already operators in the channel.

**Comment by ianbjacobs** [comment]
One suggestion we received: he bot should remove (if existing) the topic protection mode on the channel.

**Comment by tidoust** [comment]
Looking into this further, I believe the description of the issue is wrong. When the bot creates an IRC channel, it does not set any specific mode on the channel and, by default, anyone can change the channel topic. This remains the case when the bot leaves.

To end up in a situation where the topic can only be changed by channel ops, someone has to join the channel and sets the topic protection mode.

While that indeed happened during TPAC 2023, I don't think we should worry about that in practice:
* If someone set the topic protection mode **before** the bot joins, that may be for a valid reason, it seems fine that the bot cannot set the topic in that case.
* If someone sets the topic protection mode **after** the bot leaves, there's hardly anything that the bot itself can do to prevent that. An IRC server op will need to intervene if someone messes things up. Nothing specific to the bot here.

**Comment by ianbjacobs** [comment]
We conclude that there is nothing for us to fix.
