### ISSUE TITLE
Drop Agenda link?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/tpac-breakouts#53]
Our experience from TPAC 2023 suggests that the agenda link may not be very useful, and may be a common source of formatting errors.  Should the "agenda" link be dropped?

**Comment by ianbjacobs** [comment]
Other changes:

* Drop capacity from template
* Drop duration

**Comment by ianbjacobs** [comment]
Proposal:

* Drop the agenda link
* Add an Agenda section to the template, with an explanation that session chairs can either provide the agenda inline with markdown, or simply provide a link.
* The generated calendar supports both links and simple markdown, so we will use the calendar according to the issue description.

**Comment by tidoust** [comment]
Implemented in the 2024 template. Tools updated to cater for the now temporarily missing materials section.

The calendar update tool still needs to be updated to use the agenda information, instead of looking for a URL in the materials section...

**Comment by tidoust** [comment]
Calendar update tool now parses the agenda section. If that section consists of a link, it is used as the URL of the agenda. If it contains text, the text is written to the calendar entry along with the rest of the description, and the agenda URL field remains empty.

For backward compatibility, the tool also looks for an agenda URL in the materials section. That should no longer be useful (and does not need to be documented).
