### ISSUE TITLE
Should Project be in private repo?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/tpac-breakouts#57]
At first we thought the Project might be useful during the development of the schedule, and thus we made it public. That turned out to be unnecessary. Should we put the Project in a private repo (and use it to store all the private data)?

**Comment by tidoust** [comment]
> Should we put the Project in a private repo (and use it to store all the private data)?

The idea is more to make the project itself private than to put it in a private repo. Private means that it would only be visible by W3C team by default.

Now, looking into it some more, I'm not sure that's such a good idea. There are two types of private data that we need to store:
- Team-level data (Zoom meetings, mapping between chairs handle and W3C account ID), which we currently store in GitHub repository variables.
- Personal tokens/credentials, which we currently store in GitHub repository secrets.

I don't really see an easy way to store the Zoom meeting links and the chair mapping table in a project for now. We could perhaps use the project's "Readme" for that, but that seems far-fetched (and I'm not sure the Readme can be retrieved through GraphQL)
Also, I don't see how we could store real secrets in a Project.

**Comment by ianbjacobs** [comment]
Thanks for looking into this. Closing for now, then. :)

Ian
