### ISSUE TITLE
Add support for plenary session

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/tpac-breakouts#74]
Per discussion, the system should allow assignment of multiple sessions to a "plenary" block (e.g., 5 sessions in a 1-hour slot). We think there should be a single calendar entry for the plenary (not the individual sessions). But the agenda of the plenary in the calendar should name the sessions.

**Comment by tidoust** [comment]
Converting that into a semi-generic, semi-specific list of todos, that may need to be further refined:

- [ ] **Identify plenary sessions**
  A dedicated field in the issue template is probably clearer than "duration".

- [ ] **Identify plenary room**
  Default room name could be "Plenary". Non default room name could be set in the project's metadata (`plenary room: Absolutno`)

- [ ] **Define a maximum number of sessions per plenary**
  Could be set in the project's metadata (`max sessions in plenary: 5`).

- [ ] **Schedule plenary sessions first**
  Assign the plenary room to all plenary sessions.
  Choose one slot, assign the maximum number of sessions to it. Reiterate to accommodate all plenary sessions.

  *Note:* No a priori need to force a specific slot for a plenary meeting. The algorithm will just pick up one. The slot can of course be imposed afterwards by manually assigning a slot to a plenary session and regenerating the grid.

  *Note:* Scheduling plenary sessions first is required to address the next point.

- [ ] **Avoid scheduling sessions during plenary slots**
  Other rooms should remain empty during a plenary meeting.

  *Note:* From a code perspective, a slot is a plenary slot as soon as it is assigned to a session that takes place in the plenary room.

- [ ] **Maintain one calendar entry per plenary meeting**
  This calendar entry should typically list its sessions in the agenda part.

  *Note:* Switching a session from one plenary to another should be relatively straightforward, but requires updating two calendar entries (the old one and the new one).

  *Note:* Switching a session type from "breakout" to "plenary" will require custom calendar management logic, as code does not yet delete/cancel calendar entries that may have been created previously. This could perhaps remain a manual process for now.

- [ ] **Find a way to specify the order of sessions in a plenary**
  The list will appear in the calendar entry of the plenary, so we will probably want to impose a specific order.
  One possibility would be to create another custom field in the project to specify the ordering.
  Another possibility would be to create a "plenary meeting" (meta) issue for each plenary meeting when ordering needs to be further specified. This meta issue description would contain an agenda for the plenary meeting. This would also allow meeting organizers to add custom text to the plenary agenda if needed.

  *Note:* This can be addressed once other points have been addressed.
